
#language: java
#jdk: openjdk8

#install: true

#script:
#- mvn -f com.example.myproject/pom.xml clean verify




sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"

before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml

deploy:
  provider: script
  script: "mvn -B -V deploy"
  skip_cleanup: true
